language: cpp
compiler:
    - clang
script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ./TEMO
before_install:
    - sudo apt-get update -qq
install:
    - sudo apt-get install libboost-all-dev
